IsoMaker: paint::Editor Class Reference
paint::Editor Class Reference
The main class for the 2D Pixel Art Editor.
#include <2DEditor.hpp>
Public Member Functions
Editor (unsigned int screenWidth, unsigned int screenHeight)
Constructs a new Editor object.
~Editor ()
Destroys the Editor object.
void update ()
Updates the state of the editor.
void drawGrid ()
Draws the grid on the canvas.
void drawPixels ()
Draws the pixels on the canvas.
void handlePixel (int x, int y)
Handles interaction with a pixel on the canvas.
void customizationTools ()
Provides the interface for customizing tools.
void zoomIn ()
Zooms in on the canvas.
void zoomOut ()
Zooms out from the canvas.
void saveToFile (const std::string &filename)
Saves the current pixel art to a file.
void loadFromFile (const std::string &filename)
Loads pixel art from a file.
ToolType getTool () const
Gets the current tool selected.
Color getCurrentColor () const
Gets the current color.
float getZoomLevel () const
Gets the current zoom level.
int getGridSize () const
Gets the grid size.
void setTool (ToolType tool)
Sets the current tool.
void setCurrentColor (const Color &color)
Sets the current color.
void setZoomLevel (float zoomLevel)
Sets the zoom level of the canvas.
Private Member Functions
void updateCanvasOffset ()
Updates the canvas offset to center it on the screen.
Private Attributes
unsigned int _screenWidth
The width of the screen in pixels.
unsigned int _screenHeight
The height of the screen in pixels.
int _cellAmount = 20
The size of the grid cells in pixels.
Color _currentColor
The current drawing color.
float _zoomLevel = 1.0f
The current zoom level of the canvas.
const float _zoomStep = 0.1f
The zoom step value.
const int _originalGridSize = 20
The original grid size before zoom.
int _canvasOffsetX = 0
The horizontal offset for the canvas.
int _canvasOffsetY = 0
The vertical offset for the canvas.
ToolType _currentTool = ToolType::Pen
The current tool in use.
std::vector< std::vector< Color > > pixelColors
A 2D vector representing the colors of the pixels on the canvas.
Detailed Description
The main class for the 2D Pixel Art Editor.
This class provides the core functionality for creating and editing pixel art, including grid management, pixel manipulation, color customization, and file handling. It also allows for zooming and tool selection.
Definition at line 37 of file 2DEditor.hpp.
Constructor & Destructor Documentation
Editor()
paint::Editor::Editor (unsigned int screenWidth, unsigned int screenHeight) inline
Constructs a new Editor object.
Parameters
screenWidth The width of the screen in pixels.
screenHeight The height of the screen in pixels.
Initializes the editor with the given screen dimensions, setting up a default grid size and color.
Definition at line 45 of file 2DEditor.hpp.
~Editor()
paint::Editor::~Editor () inline
Destroys the Editor object.
Performs any necessary cleanup when the editor is destroyed.
Definition at line 56 of file 2DEditor.hpp.
Member Function Documentation
customizationTools()
void paint::Editor::customizationTools ()
Provides the interface for customizing tools.
Includes UI elements for selecting the current drawing tool (Pen, Eraser, or Pipette) and adjusting the current color via sliders.
Definition at line 67 of file 2DEditor.cpp.
Referenced by update().
drawGrid()
void paint::Editor::drawGrid ()
Draws the grid on the canvas.
Draws horizontal and vertical lines that represent the grid on the pixel art canvas.
Definition at line 21 of file 2DEditor.cpp.
Referenced by update().
drawPixels()
void paint::Editor::drawPixels ()
Draws the pixels on the canvas.
Renders the pixels on the canvas according to their stored colors in the pixelColors structure.
Definition at line 36 of file 2DEditor.cpp.
Referenced by update().
getCurrentColor()
Color paint::Editor::getCurrentColor () const inline
Gets the current color.
Returns
The color currently selected for drawing.
Definition at line 127 of file 2DEditor.hpp.
getGridSize()
int paint::Editor::getGridSize () const inline
Gets the grid size.
Returns
The current grid size in pixels.
Definition at line 139 of file 2DEditor.hpp.
getTool()
ToolType paint::Editor::getTool () const inline
Gets the current tool selected.
Returns
The current tool in use (Pen, Eraser, or Pipette).
Definition at line 121 of file 2DEditor.hpp.
getZoomLevel()
float paint::Editor::getZoomLevel () const inline
Gets the current zoom level.
Returns
The current zoom level of the canvas, between 0.5 and 2.0.
Definition at line 133 of file 2DEditor.hpp.
handlePixel()
void paint::Editor::handlePixel (int x, int y)
Handles interaction with a pixel on the canvas.
Parameters
x The x-coordinate of the mouse pointer (in screen space).
y The y-coordinate of the mouse pointer (in screen space).
Depending on the selected tool, this function modifies the corresponding pixel color or performs other actions.
Definition at line 47 of file 2DEditor.cpp.
Referenced by update().
loadFromFile()
void paint::Editor::loadFromFile (const std::string & filename)
Loads pixel art from a file.
Parameters
filename The filename (including path) of the image to load.
The pixel art is loaded from a PNG file, and the pixel data is stored in the pixelColors structure.
Definition at line 125 of file 2DEditor.cpp.
saveToFile()
void paint::Editor::saveToFile (const std::string & filename)
Saves the current pixel art to a file.
Parameters
filename The filename (including path) to save the pixel art image.
The image is saved as a PNG file with the provided filename.
Definition at line 109 of file 2DEditor.cpp.
setCurrentColor()
void paint::Editor::setCurrentColor (const Color & color) inline
Sets the current color.
Parameters
color The color to be selected for drawing.
Definition at line 151 of file 2DEditor.hpp.
setTool()
void paint::Editor::setTool (ToolType tool) inline
Sets the current tool.
Parameters
tool The tool to be selected (Pen, Eraser, or Pipette).
Definition at line 145 of file 2DEditor.hpp.
setZoomLevel()
void paint::Editor::setZoomLevel (float zoomLevel) inline
Sets the zoom level of the canvas.
Parameters
zoomLevel The new zoom level (between 0.5 and 2.0).
Adjusts the grid size based on the zoom level and updates the canvas offset to maintain proper centering.
Definition at line 158 of file 2DEditor.hpp.
update()
void paint::Editor::update ()
Updates the state of the editor.
Handles input events, updates the canvas, and processes tool interactions.
Definition at line 4 of file 2DEditor.cpp.
Referenced by main().
updateCanvasOffset()
void paint::Editor::updateCanvasOffset () inline private
Updates the canvas offset to center it on the screen.
The offset is recalculated based on the current grid size and screen dimensions to ensure proper alignment.
Definition at line 237 of file 2DEditor.hpp.
Referenced by Editor(), and setZoomLevel().
zoomIn()
void paint::Editor::zoomIn ()
Zooms in on the canvas.
Increases the zoom level, making the grid cells and pixels larger on the screen.
Definition at line 99 of file 2DEditor.cpp.
Referenced by update().
zoomOut()
void paint::Editor::zoomOut ()
Zooms out from the canvas.
Decreases the zoom level, making the grid cells and pixels smaller on the screen.
Definition at line 104 of file 2DEditor.cpp.
Referenced by update().
Member Data Documentation
_canvasOffsetX
int paint::Editor::_canvasOffsetX = 0 private
The horizontal offset for the canvas.
Used to center the canvas on the screen.
Definition at line 213 of file 2DEditor.hpp.
Referenced by updateCanvasOffset().
_canvasOffsetY
int paint::Editor::_canvasOffsetY = 0 private
The vertical offset for the canvas.
Used to center the canvas on the screen.
Definition at line 219 of file 2DEditor.hpp.
Referenced by updateCanvasOffset().
_currentColor
Color paint::Editor::_currentColor private
The current drawing color.
The color used for drawing on the canvas. Default value is RED.
Definition at line 189 of file 2DEditor.hpp.
Referenced by getCurrentColor(), and setCurrentColor().
_currentTool
ToolType paint::Editor::_currentTool = ToolType::Pen private
The current tool in use.
Default value is Pen. This determines what action is performed when interacting with the canvas.
Definition at line 225 of file 2DEditor.hpp.
Referenced by getTool(), and setTool().
_cellAmount
int paint::Editor::_cellAmount = 20 private
The size of the grid cells in pixels.
Default value is 20 pixels. This value is dynamically adjusted based on the zoom level.
Definition at line 183 of file 2DEditor.hpp.
Referenced by getGridSize(), setZoomLevel(), and updateCanvasOffset().
_originalGridSize
const int paint::Editor::_originalGridSize = 20 private
The original grid size before zoom.
This value is used as the baseline grid size, which is then adjusted based on the current zoom level.
Definition at line 207 of file 2DEditor.hpp.
Referenced by setZoomLevel().
_screenHeight
unsigned int paint::Editor::_screenHeight private
The height of the screen in pixels.
This value is set during the initialization of the Editor and is used to calculate the position of the grid and canvas.
Definition at line 177 of file 2DEditor.hpp.
Referenced by updateCanvasOffset().
_screenWidth
unsigned int paint::Editor::_screenWidth private
The width of the screen in pixels.
This value is set during the initialization of the Editor and is used to calculate the position of the grid and canvas.
Definition at line 171 of file 2DEditor.hpp.
Referenced by updateCanvasOffset().
_zoomLevel
float paint::Editor::_zoomLevel = 1.0f private
The current zoom level of the canvas.
Default value is 1.0 (no zoom). The zoom level can be adjusted between 0.5 and 2.0.
Definition at line 195 of file 2DEditor.hpp.
Referenced by getZoomLevel(), and setZoomLevel().
_zoomStep
const float paint::Editor::_zoomStep = 0.1f private
The zoom step value.
This is the amount by which the zoom level is adjusted when zooming in or out.
Definition at line 201 of file 2DEditor.hpp.
pixelColors
std::vector<std::vector<Color> > paint::Editor::pixelColors private
A 2D vector representing the colors of the pixels on the canvas.
Each entry in the vector corresponds to a pixel, and its color is stored as a Color object.
Definition at line 231 of file 2DEditor.hpp.
Referenced by updateCanvasOffset().
The documentation for this class was generated from the following files:
2DEditor.hpp
2DEditor.cpp