name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libgl1-mesa-dev xorg-dev

    - name: Compile IsoMaker
      run: sh install-linux.sh

    - name: Verify binary
      run: |
        if [ ! -f "bin/IsoMaker" ]; then
          echo "Compilation failed: IsoMaker binary not found."
          exit 1
        fi
      shell: bash
