name: C++ Unit Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgl1-mesa-dev xorg-dev

      - name: Install SDL2 dependencies
        run: |
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

      - name: Compile IsoMaker
        run: sh install-linux.sh

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
