name: C++ Unit Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            libgl1-mesa-dev \
            xorg-dev \
            libsdl2-dev \
            libsdl2-ttf-dev \
            libsdl2-image-dev

      - name: Configure and build tests
        run: |
          cmake -B cmake/build -S cmake -DBUILD_TESTS=ON
          cmake --build cmake/build

      - name: Run unit tests
        run: |
          cd cmake/build
          ctest --output-on-failure
